version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "php"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "1.8"
  language_version = "1.7"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"